spring:
  application:
    name: eureka-ribbon-client

server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

stores:
  ribbon:
    listOfServers: example.com,goole.com
ribbon:
  eureka:
    enabled: false
